---
title: "02b ERA5 Data"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'era5_viz.html'))})
author: "Simon Brewer"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: flatly
    df_print: paged
    number_sections: true
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries and what not

```{r message=FALSE}
## Base RF model
set.seed(42)

library(ggplot2)  # for autoplot() generic
library(dplyr)
library(sf)
library(stars)
library(tmap)
```

# Data preprocessing

## Glaciers

```{r}
dat_sf <- st_read("./data/glacier_clim.shp")
```


## Basemap

Load and crop basemap

```{r}
basemap <- read_stars("~/Dropbox/Data/summer/natural_earth/HYP_50M_SR_W/HYP_50M_SR_W.tif")

basemap2 <- st_crop(basemap, st_bbox(dat_sf))
basemap2 <- st_rgb(basemap2)
```

# ERA Data

## `t2m`

```{r}
t2m <- read_stars("~/Dropbox/Data/summer/era5/t2m_2001_2020_ann.nc")
st_crs(t2m) <- 4326
t2m <- st_crop(t2m, st_bbox(dat_sf))
t2m <- st_as_stars(t2m)
```

Make average 2006-2010
```{r}
t2m_2008 <- t2m %>% 
  slice("time", 6:10) %>%
  st_apply(MARGIN = 1:2, FUN = mean)
```

Make average 2016-2020
```{r}
t2m_2018 <- t2m %>% 
  slice("time", 16:20) %>%
  st_apply(MARGIN = 1:2, FUN = mean)
```

Make delta

```{r}
t2m_d <- t2m_2018 - t2m_2008
```

## `tp`

```{r}
tp <- read_stars("~/Dropbox/Data/summer/era5/tp_2001_2020_ann.nc")
st_crs(tp) <- 4326
tp <- st_crop(tp, st_bbox(dat_sf))
tp <- st_as_stars(tp)
```

Make average 2006-2010
```{r}
tp_2008 <- tp %>% 
  slice("time", 6:10) %>%
  st_apply(MARGIN = 1:2, FUN = mean)
```

Make average 2016-2020
```{r}
tp_2018 <- tp %>% 
  slice("time", 16:20) %>%
  st_apply(MARGIN = 1:2, FUN = mean)
```

Make delta

```{r}
tp_d <- tp_2018 - tp_2008
```

# Maps

## `t2m`

```{r message=FALSE, warning=FALSE}
x <- c(t2m_2008, t2m_2018)
names(x) <- c("t2m_2008", "t2m_2018")
m1 <- tm_shape(basemap2) +
  tm_raster(palette = "Greys", alpha = 0.5) +
  tm_shape(x) +
  tm_raster(palette = "-inferno",
            alpha = 0.75, 
            style = "quantile") +
  tm_layout(legend.outside = TRUE)
print(m1)
```

Plot $\delta$

```{r message=FALSE, warning=FALSE}
m1 <- tm_shape(basemap2) +
  tm_raster(palette = "Greys", alpha = 0.5) +
  tm_shape(t2m_d) +
  tm_raster(alpha = 0.75, 
            style = "quantile") +
  tm_layout(legend.outside = TRUE)
print(m1)
```

Plot $\delta$ with mass balance

```{r message=FALSE, warning=FALSE}
m1 <- tm_shape(t2m_d) +
  tm_raster(alpha = 0.75, 
            style = "quantile") +
  tm_shape(dat_sf) + 
    tm_symbols(col = "mb_mwea", 
             size = 0.25, 
             alpha = 0.75, 
             style = "quantile") +
  tm_layout(legend.outside = TRUE)
print(m1)
```

## `tp`

```{r message=FALSE, warning=FALSE}
x <- c(tp_2008, tp_2018)
names(x) <- c("tp_2008", "tp_2018")
m1 <- tm_shape(basemap2) +
  tm_raster(palette = "Greys", alpha = 0.5) +
  tm_shape(x) +
  tm_raster(palette = "YlGnBu",
            alpha = 0.75, 
            style = "quantile") +
  tm_layout(legend.outside = TRUE)
print(m1)
```

Plot $\delta$

```{r message=FALSE, warning=FALSE}
m1 <- tm_shape(basemap2) +
  tm_raster(palette = "Greys", alpha = 0.5) +
  tm_shape(tp_d) +
  tm_raster(alpha = 0.75, 
            style = "quantile") +
  tm_layout(legend.outside = TRUE)
print(m1)
```

Plot $\delta$ with mass balance

```{r message=FALSE, warning=FALSE}
m1 <- tm_shape(tp_d) +
  tm_raster(alpha = 0.75, 
            style = "quantile") +
  tm_shape(dat_sf) + 
    tm_symbols(col = "mb_mwea", 
             size = 0.25, 
             alpha = 0.75, 
             style = "quantile") +
  tm_layout(legend.outside = TRUE)
print(m1)
```
